cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
  paths:
    - .composer/
    - .php_cs.cache

variables:
  COMPOSER_CACHE_DIR: ".composer"
  TYPO3_PATH_WEB: "$CI_PROJECT_DIR/.build/public"
  MYSQL_DATABASE: "typo3"
  MYSQL_ROOT_PASSWORD: "joh316"
  typo3DatabaseName: "typo3"
  typo3DatabaseHost: "mysql"
  typo3DatabaseUsername: "root"
  typo3DatabasePassword: "joh316"

before_script:
  - apk add git --update

stages:
  - lint
  - documentation
  - analysis

lint:cgl:
  image: $CI_REGISTRY/containers/phpunit-with-php-8.2:main
  stage: lint
  before_script:
    - composer remove typo3/cms-core --no-update
    - composer config --no-plugins allow-plugins.sbuerk/typo3-cmscomposerinstallers-testingframework-bridge true
    - composer install --no-progress --no-ansi --no-interaction
  script:
    - vendor/bin/php-cs-fixer fix --config=Build/.php-cs-fixer.dist.php -v --dry-run --using-cache=no --path-mode=intersection ./
    - vendor/bin/typoscript-lint -c Build/typoscriptlint.yaml Configuration

lint:yaml:
  stage: lint
  image: python:alpine3.7
  before_script:
    - pip install yamllint==1.10.0
  script:
    - yamllint -c Build/yamllint.yaml Configuration/ Resources/

.lint_php: &lint_php
  stage: lint
  image: $CONTAINER_IMAGE
  script:
    - find *.php Classes Configuration -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l

lint:php82:
  <<: *lint_php
  variables:
    CONTAINER_IMAGE: php:8.2-alpine

lint:php83:
  <<: *lint_php
  variables:
    CONTAINER_IMAGE: php:8.3-alpine

phpstan:analyse:
  image: $CI_REGISTRY/containers/phpunit-with-php-8.2:main
  stage: lint
  before_script:
    - sed -i -e "s#ssh://git@code.extco.de:22722#https://gitlab-ci-token:$CI_JOB_TOKEN@code.extco.de#g" composer.json
    - composer config platform.php 8.2
    - composer install --no-progress --no-ansi --no-interaction
  script:
    - vendor/bin/phpstan analyse -c Build/phpstan.neon --memory-limit 256M

documentation:
  stage: documentation
  image:
    name: ghcr.io/typo3-documentation/render-guides:latest
    entrypoint: [ "" ]
  script:
    - mkdir -p Documentation-GENERATED-temp
    - /opt/guides/entrypoint.sh --config=Documentation --no-progress --fail-on-log
  before_script: []
  artifacts:
    paths:
      - Documentation-GENERATED-temp/
    expire_in: 1 day
    when: always
