services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Extcode\CartGirosolution\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Configuration/*'

  Extcode\CartGirosolution\EventListener\Order\Payment\ClearCart:
    tags:
      - name: event.listener
        identifier: 'cart-girosolution--order--payment--clear-cart'
        event: Extcode\Cart\Event\Order\PaymentEvent
        before: 'cart-girosolution--order--payment--provider-redirect'

  Extcode\CartGirosolution\EventListener\Order\Payment\ProviderRedirect:
    tags:
      - name: event.listener
        identifier: 'cart-girosolution--order--payment--provider-redirect'
        event: Extcode\Cart\Event\Order\PaymentEvent

  Extcode\CartGirosolution\EventListener\Order\Finish\Email:
    class: 'Extcode\Cart\EventListener\Order\Finish\Email'
    tags:
      - name: event.listener
        identifier: 'cart-girosolution--order--finish--email'
        event: Extcode\CartGirosolution\Event\Order\FinishEvent
