# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2019-2022
  project: Cart Girosolution
  version: 1.0
  release: 1.0.0